# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: false
dist: trusty
notifications:
    on_success: never
    on_failure: true
install:
  # Install conda
  - pip install conda